---
name: Terraform
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  module-validation:
    uses: appvia/appvia-cicd-workflows/.github/workflows/terraform-module-validation.yml@0cd74ac5b197bb83f63ec6df2a28d761381eb06d # main
    name: Module Validation
    with:
      working-directory: .
