---
name: Terraform
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  module-validation:
    uses: appvia/appvia-cicd-workflows/.github/workflows/terraform-module-validation.yml@f30d1ecbc7f79ff2248b29959a700a5661b82ab5 # main
    name: Module Validation
    with:
      working-directory: .
