---
name: Terraform
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  module-validation:
    uses: appvia/appvia-cicd-workflows/.github/workflows/terraform-module-validation.yml@9b6a5fd5f2fdcb76246ec73dbac6cb888f0fdf12 # main
    name: Module Validation
    with:
      working-directory: .
